changeLogFile=db.changelog-master.xml
url=jdbc:mysql://db:3306/cafeteria_db?useSSL=false&allowPublicKeyRetrieval=true
username=root
password=root123
driver=com.mysql.cj.jdbc.Driver
classpath=/liquibase/changelog/mysql-connector-j.jar